'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\Server1\Movies\")>  _
        Public Property DefaultMoviePath() As String
            Get
                Return CType(Me("DefaultMoviePath"),String)
            End Get
            Set
                Me("DefaultMoviePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\AMC\Media Database.xml")>  _
        Public Property DefaultXMLPath() As String
            Get
                Return CType(Me("DefaultXMLPath"),String)
            End Get
            Set
                Me("DefaultXMLPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("HDD")>  _
        Public Property DefaultMediaType() As String
            Get
                Return CType(Me("DefaultMediaType"),String)
            End Get
            Set
                Me("DefaultMediaType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Server")>  _
        Public Property DefaultMediaLabel() As String
            Get
                Return CType(Me("DefaultMediaLabel"),String)
            End Get
            Set
                Me("DefaultMediaLabel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultOverridePath() As String
            Get
                Return CType(Me("DefaultOverridePath"),String)
            End Get
            Set
                Me("DefaultOverridePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("avi;mpg;divx;mpeg;wmv")>  _
        Public Property FileTypesToCheck() As String
            Get
                Return CType(Me("FileTypesToCheck"),String)
            End Get
            Set
                Me("FileTypesToCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DefaultBackupXML() As Boolean
            Get
                Return CType(Me("DefaultBackupXML"),Boolean)
            End Get
            Set
                Me("DefaultBackupXML") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DefaultOverwriteXML() As Boolean
            Get
                Return CType(Me("DefaultOverwriteXML"),Boolean)
            End Get
            Set
                Me("DefaultOverwriteXML") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Source")>  _
        Public Property AMCDatabaseSource() As String
            Get
                Return CType(Me("AMCDatabaseSource"),String)
            End Get
            Set
                Me("AMCDatabaseSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DefaultPurgeMissing() As Boolean
            Get
                Return CType(Me("DefaultPurgeMissing"),Boolean)
            End Get
            Set
                Me("DefaultPurgeMissing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("iso;img")>  _
        Public Property FileTypesNonMedia() As String
            Get
                Return CType(Me("FileTypesNonMedia"),String)
            End Get
            Set
                Me("FileTypesNonMedia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("[0-9]of[0-9]")>  _
        Public Property RegExCheckMultiPart() As String
            Get
                Return CType(Me("RegExCheckMultiPart"),String)
            End Get
            Set
                Me("RegExCheckMultiPart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DefaultScanDVDFolders() As String
            Get
                Return CType(Me("DefaultScanDVDFolders"),String)
            End Get
            Set
                Me("DefaultScanDVDFolders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ExecuteProgram() As Boolean
            Get
                Return CType(Me("ExecuteProgram"),Boolean)
            End Get
            Set
                Me("ExecuteProgram") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ExecuteProgramPath() As String
            Get
                Return CType(Me("ExecuteProgramPath"),String)
            End Get
            Set
                Me("ExecuteProgramPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ExecuteOnlyForOrphans() As Boolean
            Get
                Return CType(Me("ExecuteOnlyForOrphans"),Boolean)
            End Get
            Set
                Me("ExecuteOnlyForOrphans") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("All Events")>  _
        Public Property LogLevel() As String
            Get
                Return CType(Me("LogLevel"),String)
            End Get
            Set
                Me("LogLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("File Created Date")>  _
        Public Property DateHandling() As String
            Get
                Return CType(Me("DateHandling"),String)
            End Get
            Set
                Me("DateHandling") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultParserPath() As String
            Get
                Return CType(Me("DefaultParserPath"),String)
            End Get
            Set
                Me("DefaultParserPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ShortNames() As Boolean
            Get
                Return CType(Me("ShortNames"),Boolean)
            End Get
            Set
                Me("ShortNames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\AMC\AMCUpdater_Excluded_Files.xml")>  _
        Public Property DefaultExcludeFile() As String
            Get
                Return CType(Me("DefaultExcludeFile"),String)
            End Get
            Set
                Me("DefaultExcludeFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property BatchMode() As Boolean
            Get
                Return CType(Me("BatchMode"),Boolean)
            End Get
            Set
                Me("BatchMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Date|True;Rating|True;Year|True;Length|True;VideoBitrate|True;AudioBitrate|True;D"& _ 
            "isks|True;Checked|True;MediaLabel|True;MediaType|True;OriginalTitle|True;Transla"& _ 
            "tedTitle|True;Director|True;Producer|True;Country|True;Category|True;Actors|True"& _ 
            ";URL|True;Description|True;Comments|True;VideoFormat|True;AudioFormat|True;Resol"& _ 
            "ution|True;Framerate|True;Languages|True;Subtitles|True;Size|True;Picture|True")>  _
        Public Property DatabaseFields() As String
            Get
                Return CType(Me("DatabaseFields"),String)
            End Get
            Set
                Me("DatabaseFields") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ImportFileOnInternetLookupFailure() As Boolean
            Get
                Return CType(Me("ImportFileOnInternetLookupFailure"),Boolean)
            End Get
            Set
                Me("ImportFileOnInternetLookupFailure") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AMCUpdater.My.MySettings
            Get
                Return Global.AMCUpdater.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
